# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-01 06:48
from __future__ import unicode_literals

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile', models.IntegerField(default=0, verbose_name='\u624b\u673a\u53f7')),
                ('sex', models.IntegerField(default=0, verbose_name='\u6027\u522b: 0\u5973 1\u7537')),
                ('info_status', models.IntegerField(default=0, verbose_name='\u8d26\u53f7\u72b6\u6001: 0\u5df2\u6ce8\u518c\uff0c1\u5df2\u63d0\u4ea4\u4fe1\u606f\uff0c2\u5df2\u5b9e\u540d\u5236\uff0c-1\u4fe1\u606f\u5df2\u8fc7\u671f\uff08\u975e\u604b\u7231\u72b6\u6001\u540c\u65f6\u4e00\u5e74\u5185\u672a\u767b\u9646\u7f51\u7ad9\uff09\uff0c-2\u5df2\u88ab\u6295\u8bc9\uff0c-3\u5df2\u88ab\u5c01\u53f7')),
                ('love_status', models.IntegerField(default=0, verbose_name='\u604b\u7231\u72b6\u6001\uff1a0\u672a\u627e\u5230\uff0c1\u5df2\u63a5\u89e6\uff0c2\u4e0d\u5408\u9002\uff0c3\u5df2\u604b\u7231\uff0c4\u5df2\u5206\u624b')),
                ('city', models.CharField(default='', max_length=100, verbose_name='\u57ce\u5e02\u540d')),
                ('school', models.CharField(default='', max_length=100, verbose_name='\u5b66\u6821\u540d')),
                ('stature', models.IntegerField(default=0, verbose_name='\u8eab\u9ad8(cm)')),
                ('weight', models.IntegerField(default=0, verbose_name='\u4f53\u91cd(kg)')),
                ('appearance', models.IntegerField(default=0, verbose_name='\u76f8\u8c8c: 0\u4e0d\u8981\u6c42\uff0c1\u5e72\u51c0\u6574\u6d01\uff0c2\u9633\u5149\u81ea\u4fe1\uff0c3\u82f1\u4fca\u5e05\u6c14\uff0c12\uff0c13\uff0c23\u4e3a\u7ec4\u5408...')),
                ('character', models.IntegerField(default=0, verbose_name='\u6027\u683c\uff1a1\u66b4\u8e81\uff0c2\u6e29\u67d4\uff0c3\u7ec6\u5fc3\uff0c4...')),
                ('hobby', models.IntegerField(default=0, verbose_name='\u5174\u8da3\uff1a0\u65e0\uff0c1\u52a8\u6f2b\uff0c2\u8db3\u7403\uff0c3\u4e52\u4e53\u7403\uff0c4...')),
                ('speciality', models.CharField(default=0, max_length=100, verbose_name='\u7279\u957f\uff1a0\u65e0\uff0c1\u5409\u4ed6\uff0c2\u8bd7\u8bcd\uff0c3\u54f2\u5b66\uff0c4\u753b\u753b\uff0c5...')),
                ('habit', models.IntegerField(default=0, verbose_name='\u4e60\u60ef\uff1a0\u65e0\uff0c...')),
                ('disgust', models.IntegerField(default=0, verbose_name='\u538c\u6076\u7684\u4e8b\u60c5\uff1a0\u65e0\uff0c1\u5a18\u5a18\u8154\uff0c2\u5c0f\u6c14\u9b3c\uff0c3\u810f\u8bdd\u8fde\u7bc7\uff0c4\u4e0d\u5b88\u4fe1\u7528\uff0c5...')),
                ('wealth', models.IntegerField(default=0, verbose_name='\u8d22\u5bcc\uff1a\u6bcf\u6708\u751f\u6d3b\u8d39\u591a\u5c11\u5143')),
                ('custom', models.CharField(default='', max_length=255, verbose_name='\u81ea\u5b9a\u4e49\u7684\u7537\u751f\u7684\u63cf\u8ff0\u4eba\u751f\u7406\u60f3\u554a\u5565\u7684\u6216\u5973\u751f\u81ea\u5b9a\u4e49\u7684\u4e00\u4e9b\u8981\u6c42')),
                ('threshold_fee', models.IntegerField(default=10, verbose_name='\u95e8\u69db\u8d39')),
                ('student_identity_card_qiniu_uri', models.CharField(default='', max_length=500, verbose_name='\u5b66\u751f\u8bc1\u7167\u7247\u4e03\u725b\u4e91\u5b58\u50a8\u5bf9\u5e94\u7684uri')),
                ('name', models.CharField(default='', max_length=20, verbose_name='\u59d3\u540d')),
                ('age', models.IntegerField(default=0, verbose_name='\u5e74\u9f84')),
                ('college', models.CharField(default='', max_length=100, verbose_name='\u9662\u7cfb\u540d')),
                ('profession', models.CharField(default='', max_length=100, verbose_name='\u4e13\u4e1a\u540d')),
                ('school_num', models.CharField(default='', max_length=100, verbose_name='\u5b66\u53f7')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'verbose_name': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MessageCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u8bb0\u5f55\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('user_id', models.IntegerField(default=0, verbose_name='uid')),
                ('usage', models.IntegerField(default=0, verbose_name='\u7528\u9014\uff1a0\u767b\u9646\uff0c1\u63a8\u8350\u901a\u77e5\uff0c2...')),
                ('mobile', models.IntegerField(default=0, verbose_name='\u624b\u673a\u53f7')),
                ('code', models.IntegerField(default=0, verbose_name='\u56db\u4f4d\u77ed\u4fe1\u7801')),
            ],
            options={
                'db_table': 'message_code',
            },
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u8bb0\u5f55\u65f6\u95f4')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u4fee\u6539\u65e5\u671f')),
                ('boy_id', models.IntegerField(default=0, verbose_name='\u7537\u5b69id')),
                ('girl_id', models.IntegerField(default=0, verbose_name='\u5973\u5b69id')),
                ('relation', models.IntegerField(default=0, verbose_name='0\u5df2\u901a\u77e5/1\u5df2\u67e5\u9605/2\u5df2\u9080\u8bf7/3\u5df2\u63a5\u89e6/4\u5df2\u604b\u7231/5\u5df2\u5206\u624b/6\u5df2\u6295\u8bc9')),
            ],
            options={
                'db_table': 'user_relation',
            },
        ),
    ]
