# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='love_status',
        ),
        migrations.AddField(
            model_name='users',
            name='real_name_status',
            field=models.IntegerField(default=0, verbose_name='\u604b\u7231\u72b6\u6001\uff1a0\u672a\u5b9e\u540d\uff0c1\u4e00\u7ea7\u5b9e\u540d\uff0c2\u4e8c\u7ea7\u5b9e\u540d\uff0c3\u4e09\u7ea7\u5b9e\u540d\uff0c4\u56db\u7ea7\u5b9e\u540d'),
        ),
        migrations.AlterField(
            model_name='users',
            name='info_status',
            field=models.IntegerField(default=0, verbose_name='\u8d26\u53f7\u72b6\u6001: 0\u5df2\u6ce8\u518c\uff0c1\u5b8c\u5584\uff0c2\u5df2\u63a5\u89e6\uff0c3\u5df2\u604b\u7231\uff0c-1\u5df2\u8fc7\u671f\uff0c-2\u5df2\u6295\u8bc9\uff0c-3\u5df2\u88ab\u6295\u8bc9'),
        ),
    ]
