# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
        migrations.AddField(
            model_name='users',
            name='info_status',
            field=models.IntegerField(default=0, verbose_name='\u8d26\u53f7\u72b6\u6001: 0\u5df2\u6ce8\u518c\uff0c1\u5df2\u63d0\u4ea4\u4fe1\u606f\uff0c2\u5df2\u5b9e\u540d\u5236\uff0c-1\u4fe1\u606f\u5df2\u8fc7\u671f\uff08\u975e\u604b\u7231\u72b6\u6001\u540c\u65f6\u4e00\u5e74\u5185\u672a\u767b\u9646\u7f51\u7ad9\uff09\uff0c-2\u5df2\u88ab\u6295\u8bc9\uff0c-3\u5df2\u88ab\u5c01\u53f7'),
        ),
        migrations.AddField(
            model_name='users',
            name='love_status',
            field=models.IntegerField(default=0, verbose_name='\u604b\u7231\u72b6\u6001\uff1a0\u672a\u627e\u5230\uff0c1\u5df2\u63a5\u89e6\uff0c2\u4e0d\u5408\u9002\uff0c3\u5df2\u604b\u7231\uff0c4\u5df2\u5206\u624b'),
        ),
        migrations.AlterField(
            model_name='users',
            name='custom',
            field=models.CharField(default='', max_length=255, verbose_name='\u81ea\u5b9a\u4e49\u7684\u7537\u751f\u7684\u63cf\u8ff0\u4eba\u751f\u7406\u60f3\u554a\u5565\u7684\u6216\u5973\u751f\u81ea\u5b9a\u4e49\u7684\u4e00\u4e9b\u8981\u6c42'),
        ),
    ]
