# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niceapp', '0002_auto_20180102_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.IntegerField(default=0, verbose_name='\u57ce\u5e02\u540d:0\u5317\u4eac,1\u4e0a\u6d77...'),
        ),
    ]
