# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niceapp', '0003_users_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='niceapp.BaseModel')),
                ('boy_id', models.IntegerField(default=0, verbose_name='\u7537\u5b69id')),
                ('girl_id', models.IntegerField(default=0, verbose_name='\u5973\u5b69id')),
                ('relation', models.IntegerField(default=0, verbose_name='0\u5df2\u901a\u77e5/1\u5df2\u67e5\u9605/2\u5df2\u9080\u8bf7/3\u5df2\u63a5\u89e6/4\u5df2\u604b\u7231/5\u5df2\u5206\u624b/6\u5df2\u6295\u8bc9')),
            ],
            bases=('niceapp.basemodel',),
        ),
    ]
