# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 02:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niceapp', '0005_messagecode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='basemodel_ptr',
        ),
        migrations.AddField(
            model_name='messagecode',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='uid'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='messagecode',
            table='message_code',
        ),
        migrations.AlterModelTable(
            name='userrelation',
            table='user_relation',
        ),
    ]
